### ISSUE TITLE
replace [generate markers] with comments

### ISSUE THREAD

**Issue by jam01** [MS3Inc/camel-archetypes#5]
since the route generations is now independent, we should replace the markers for comments so the generated code is compilable in case someone does not wish to use our plugin to generate their routes.

**Comment by rlratcliffe** [comment]
In order to make the project compilable without the plugin and to maintain the same structure as what is generated, we will need

- [ ] a rest() route with a producer in RoutesGenerated
- [ ] a consumer route in RoutesImplementation
- [ ] a sample api (greeting.yaml in the tests) in `generated/api` and an interceptFrom in RoutesGenerated
